### ISSUE TITLE
Cleaner, bug with new version of PHPSECLIB3

### ISSUE THREAD

**Issue by Esysteme** [PmaControl/PmaControl#61]
```
Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202
╔═══════╦══════════════╗
║ Table ║ Rows deleted ║
╠═══════╬══════════════╣
║ logs  ║ 1000         ║
╚═══════╩══════════════╝

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202
╔═══════╦══════════════╗
║ Table ║ Rows deleted ║
╠═══════╬══════════════╣
║ logs  ║ 1000         ║
╚═══════╩══════════════╝

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202
╔═══════╦══════════════╗
║ Table ║ Rows deleted ║
╠═══════╬══════════════╣
║ logs  ║ 1000         ║
╚═══════╩══════════════╝

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202
╔═══════╦══════════════╗
║ Table ║ Rows deleted ║
╠═══════╬══════════════╣
║ logs  ║ 1000         ║
╚═══════╩══════════════╝

Warning: mysqli_connect(): (HY000/2002): Connection refused in /srv/www/pmacontrol/vendor/glial/glial/Glial/Sgbd/Sql/Mysql/Mysql.php on line 71
[2023-02-24 19:29:32][ERROR] GLI-012 : Can't connect to (pmacontrol@127.0.0.1:3306) MySQL server {mysqli_connect(): (HY000/2002): Connection refused} 
CODE ERROR : 80

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Notice: Undefined offset: 0 in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3442

Warning: count(): Parameter must be an array or an object that implements Countable in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3442

Notice: Undefined index: local in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/pmacontrol/App/Controller/Cleaner.php on line 3202

Fatal error: Uncaught Error: Call to undefined method phpseclib3\Net\SFTP::size() in /srv/www/pmacontrol/App/Library/Scp.php:78
Stack trace:
#0 /srv/www/pmacontrol/App/Controller/Cleaner.php(2345): App\Controller\Cleaner->sendFile('1', '/srv/www/pmacon...', '/backup/pmacont...')
#1 /srv/www/pmacontrol/App/Controller/Cleaner.php(727): App\Controller\Cleaner->pushArchive()
#2 /srv/www/pmacontrol/vendor/glial/glial/Glial/Synapse/Controller.php(118): App\Controller\Cleaner->launch(Array)
#3 /srv/www/pmacontrol/vendor/glial/glial/Glial/Synapse/FactoryController.php(68): Glial\Synapse\Controller->getController()
#4 /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php(239): Glial\Synapse\FactoryController::rootNode('Cleaner', 'launch', Array)
#5 /srv/www/pmacontrol/App/Webroot/index.php(99): include('/srv/www/pmacon...')
#6 {main}
  thrown in /srv/www/pmacontrol/App/Library/Scp.php on line 78

**Comment by Esysteme** [comment]
Fixed: phpseclib v3.0 is properly integrated (composer.json line 29). DeployRsaKey uses v3 imports. No phpseclib usage remains in Cleaner.php.
