### ISSUE TITLE
Notice to fix PHP 7.4

### ISSUE THREAD

**Issue by Esysteme** [PmaControl/PmaControl#63]
```
#0 /srv/www/pmacontrol/App/Webroot/index.php(99): include()
#1 {main}
  thrown in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:47:25 Europe/Berlin] PHP Notice:  Undefined variable: _DB in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:47:25 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function sql() on null in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php:220
Stack trace:
#0 /srv/www/pmacontrol/App/Webroot/index.php(99): include()
#1 {main}
  thrown in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
```

**Comment by Esysteme** [comment]
```
[06-Oct-2023 10:40:32 Europe/Berlin] PHP Warning:  Use of undefined constant LOG_FILE - assumed 'LOG_FILE' (this will throw an Error in a future version of PHP) in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 55
[06-Oct-2023 10:41:19 Europe/Berlin] PHP Notice:  Undefined variable: _DB in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:41:19 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function sql() on null in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php:220
Stack trace:
#0 /srv/www/pmacontrol/App/Webroot/index.php(99): include()
#1 {main}
  thrown in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:43:57 Europe/Berlin] PHP Notice:  Undefined variable: _DB in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:43:57 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function sql() on null in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php:220
Stack trace:
#0 /srv/www/pmacontrol/App/Webroot/index.php(99): include()
#1 {main}
  thrown in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:44:34 Europe/Berlin] PHP Fatal error:  Uncaught Error: Object of class Glial\Sgbd\Sql\Mysql\Mysql could not be converted to string in /srv/www/pmacontrol/App/Library/Mysql.php:133
Stack trace:
#0 /srv/www/pmacontrol/App/Library/Mysql.php(67): App\Library\Mysql::addMaxDate()
#1 /srv/www/pmacontrol/App/Controller/Mysql.php(1080): App\Library\Mysql::onAddMysqlServer()
#2 /srv/www/pmacontrol/vendor/glial/glial/Glial/Synapse/Controller.php(101): App\Controller\Mysql->add()
#3 /srv/www/pmacontrol/vendor/glial/glial/Glial/Synapse/FactoryController.php(68): Glial\Synapse\Controller->getController()
#4 /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php(239): Glial\Synapse\FactoryController::rootNode()
#5 /srv/www/pmacontrol/App/Webroot/index.php(99): include('/srv/www/pmacon...')
#6 {main}
  thrown in /srv/www/pmacontrol/App/Library/Mysql.php on line 133
[06-Oct-2023 10:45:22 Europe/Berlin] PHP Notice:  Undefined variable: _DB in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:45:22 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function sql() on null in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php:220
Stack trace:
#0 /srv/www/pmacontrol/App/Webroot/index.php(99): include()
#1 {main}
  thrown in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:47:25 Europe/Berlin] PHP Notice:  Undefined variable: _DB in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220
[06-Oct-2023 10:47:25 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function sql() on null in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php:220
Stack trace:
#0 /srv/www/pmacontrol/App/Webroot/index.php(99): include()
#1 {main}
  thrown in /srv/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php on line 220

**Comment by Esysteme** [comment]
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: url in /srv/www/pmacontrol/App/view/Database/index.view.php on line 28
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: menu in /srv/www/pmacontrol/App/view/Database/index.view.php on line 17
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: count in /srv/www/pmacontrol/App/view/Database/index.view.php on line 24
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: url in /srv/www/pmacontrol/App/view/Database/index.view.php on line 28
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: menu in /srv/www/pmacontrol/App/view/Database/index.view.php on line 17
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: count in /srv/www/pmacontrol/App/view/Database/index.view.php on line 24
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: url in /srv/www/pmacontrol/App/view/Database/index.view.php on line 28
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: menu in /srv/www/pmacontrol/App/view/Database/index.view.php on line 17
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: count in /srv/www/pmacontrol/App/view/Database/index.view.php on line 24
[20-Oct-2023 01:34:28 Europe/Berlin] PHP Notice:  Undefined index: url in /srv/www/pmacontrol/App/view/Database/index.view.php on line 28





[20-Oct-2023 01:46:08 Europe/Berlin] PHP Notice:  Undefined variable: modes in /srv/www/pmacontrol/App/Controller/Benchmark.php on line 1109
[20-Oct-2023 01:46:08 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/pmacontrol/App/Controller/Benchmark.php on line 1109
[20-Oct-2023 01:46:46 Europe/Berlin] PHP Notice:  Undefined variable: modes in /srv/www/pmacontrol/App/Controller/Benchmark.php on line 1109
[20-Oct-2023 01:46:46 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/pmacontrol/App/Controller/Benchmark.php on line 1109
[20-Oct-2023 01:46:47 Europe/Berlin] PHP Notice:  Undefined variable: modes in /srv/www/pmacontrol/App/Controller/Benchmark.php on line 1109
[20-Oct-2023 01:46:47 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/pmacontrol/App/Controller/Benchmark.php on line 1109

**Comment by Esysteme** [comment]
fixed all
